# Generated by Django 4.1 on 2023-06-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=50)),
                ("task_description", models.CharField(max_length=250)),
                ("create_date", models.DateTimeField(verbose_name="Date made")),
                (
                    "due_date",
                    models.DateTimeField(verbose_name="Task due date and time"),
                ),
                ("done", models.BooleanField(verbose_name="Task id done")),
            ],
        ),
    ]
